project:
  type: website
  resources:
    - fonts/*
  output-dir: dist

website:
  title: "GoogleFontIssue"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [darkly, custom.scss]
    css: styles.css
    toc: true
