project:
  type: website
  output-dir: dist  

website:
  title: "GoogleFontIssue"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: [darkly, custom]
    css: styles.css
    toc: true



